# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_LM <- function(YY, XX, var_groups, test_type0 = 1L, ncores = 1L) {
    .Call('_CSeQTL_Rcpp_LM', PACKAGE = 'CSeQTL', YY, XX, var_groups, test_type0, ncores)
}

Rcpp_CSeQTL_FDR <- function(pvalues, lambda = 0.5, ncores = 1L) {
    .Call('_CSeQTL_Rcpp_CSeQTL_FDR', PACKAGE = 'CSeQTL', pvalues, lambda, ncores)
}

Rcpp_CSeQTL_profile_PAR <- function(TREC, hap2, ASREC, PHASE, SNP, RHO, XX, upPARS, index, bounds, max_iter = 4e3L, eps = 1e-10, ncores = 1L, show = TRUE) {
    .Call('_CSeQTL_Rcpp_CSeQTL_profile_PAR', PACKAGE = 'CSeQTL', TREC, hap2, ASREC, PHASE, SNP, RHO, XX, upPARS, index, bounds, max_iter, eps, ncores, show)
}

Rcpp_CSeQTL_profile_PARS <- function(TREC, hap2, ASREC, PHASE, SNP, RHO, XX, upPARS, bounds, max_iter = 4e3L, eps = 1e-10, ncores = 1L, show = TRUE) {
    .Call('_CSeQTL_Rcpp_CSeQTL_profile_PARS', PACKAGE = 'CSeQTL', TREC, hap2, ASREC, PHASE, SNP, RHO, XX, upPARS, bounds, max_iter, eps, ncores, show)
}

Rcpp_CSeQTL_cooksD <- function(TREC, RHO, XX, trim_thres, max_iter = 4e3L, eps = 1e-10, mad_const = 1.4826, ncores = 1L, gr_eps = 1e-2, conv_eps = 5e-5, show = TRUE) {
    .Call('_CSeQTL_Rcpp_CSeQTL_cooksD', PACKAGE = 'CSeQTL', TREC, RHO, XX, trim_thres, max_iter, eps, mad_const, ncores, gr_eps, conv_eps, show)
}

Rcpp_CSeQTL_BFGS_smart <- function(TREC, hap2, ASREC, PHASE_0, SNP, RHO, XX, upPARS_0, iFullModel = TRUE, trim = TRUE, trim_thres = 10, hypotest = FALSE, swap = TRUE, numAS = 5L, numASn = 10L, numAS_het = 5L, mad_const = 1.4826, max_iter = 4e3L, eps = 1e-10, ncores = 1L, gr_eps = 1e-2, conv_eps = 5e-5, hess_shift = 1e-5, show = TRUE) {
    .Call('_CSeQTL_Rcpp_CSeQTL_BFGS_smart', PACKAGE = 'CSeQTL', TREC, hap2, ASREC, PHASE_0, SNP, RHO, XX, upPARS_0, iFullModel, trim, trim_thres, hypotest, swap, numAS, numASn, numAS_het, mad_const, max_iter, eps, ncores, gr_eps, conv_eps, hess_shift, show)
}

Rcpp_CSeQTL_GS <- function(XX, TREC_0, SNP, hap2, ASREC, PHASE_0, RHO, GS_index, trim = TRUE, swapCT = TRUE, trim_thres = 10, numAS = 5L, numASn = 5L, numAS_het = 5L, cistrans = 0.01, mad_const = 1.4826, max_iter = 4e3L, eps = 1e-10, gr_eps = 1e-2, conv_eps = 5e-5, show = TRUE, prompt = TRUE, ncores = 1L) {
    .Call('_CSeQTL_Rcpp_CSeQTL_GS', PACKAGE = 'CSeQTL', XX, TREC_0, SNP, hap2, ASREC, PHASE_0, RHO, GS_index, trim, swapCT, trim_thres, numAS, numASn, numAS_het, cistrans, mad_const, max_iter, eps, gr_eps, conv_eps, show, prompt, ncores)
}

Rcpp_calc_GI <- function(PP, QQ) {
    .Call('_CSeQTL_Rcpp_calc_GI', PACKAGE = 'CSeQTL', PP, QQ)
}

Rcpp_CSeQTL_MU <- function(GI, PARS) {
    .Call('_CSeQTL_Rcpp_CSeQTL_MU', PACKAGE = 'CSeQTL', GI, PARS)
}

Rcpp_calc_MAF_all <- function(SNP, phasing = TRUE, show = TRUE, ncores = 1L) {
    .Call('_CSeQTL_Rcpp_calc_MAF_all', PACKAGE = 'CSeQTL', SNP, phasing, show, ncores)
}

Rcpp_NB_reg_one <- function(YY, XX, OO, max_iter = 4e3L, eps = 1e-5, show = TRUE) {
    .Call('_CSeQTL_Rcpp_NB_reg_one', PACKAGE = 'CSeQTL', YY, XX, OO, max_iter, eps, show)
}

